### ISSUE TITLE
login fail

### ISSUE THREAD

**Issue by ivan-etoku** [imr-framework/vs-tabletop#3]
im using chrome to access the games
i have to register eachtime while accessing the games(after closing the browser),i use the same username and password but still fails
![image](https://user-images.githubusercontent.com/123539537/218977609-dad61208-2802-4007-933c-7e687a6f05a4.png)

**Comment by sairamgeethanath** [comment]
Trying to figure it it is a Heroku end issue or VS issue. Can you please let me know if this was tried locally or on heroku.

**Comment by sairamgeethanath** [comment]
### On Heroku - 
    a. Within a browser session, the login holds. To check, do the following
    1.  Open a browser and register (green font in the picture)
    
![image](https://github.com/imr-framework/vs-tabletop/assets/30870273/c8c17a8f-3004-4563-a8da-9cc4d715c44b)
     2. Note that we do not ask for your email address to ping later
     3. Login with the credentials
     4. Logout of the website
     5. Login with any of the other tabs with the same username/password
     6. If you close the browser, then the database that was created also gets deleted. This is the maximum we can do with a free distribution on Heroku

**Comment by sairamgeethanath** [comment]
### Pip install or Cloning 
1. You should be able to use credentials as long as the database file is on the same local system which acts as the server
2. If the server is stopped and restarted, you should still be able to reuse the old credentials
3. To reproduce and check, run app.py and register a user "local" with password "4$3#2@" 
4.  Login with those credentials and then logout.
5.  Login again with the same credentials - you should be able to successfully login. 

This is because the user info is stored on the server (your local machine) and hence can be accessed. 
7. Now stop the server from your python IDE or the terminal by <control + C>
8. Run app.py again and login with the 'local' user. You should be able to login.
